'use client';
import {mergeCloudModels} from '@/lib/merge-cloud-models';
import {migrateLegacyCalendar} from '@/lib/calendar-migration';
import {create} from 'zustand';
import {persist} from 'zustand/middleware';
import {FinancialModel} from '@/types/model';
import {migrateWorkforce} from '@/lib/workforce';
import {demoModel,id} from '@/lib/demo';
export interface Version {id:string;name:string;date:string;model:FinancialModel}
interface Store {models:FinancialModel[];activeId:string;versions:Version[];savedAt:string;importModel:(model:FinancialModel)=>void;setModel:(model:FinancialModel)=>void;selectModel:(id:string)=>void;newModel:()=>void;saveVersion:(name:string)=>void;restore:(id:string)=>void;loadCloud:(models:FinancialModel[])=>void;mergeVersions:(versions:Version[])=>void}
export const useModels=create<Store>()(persist((set,get)=>{const demo=migrateWorkforce(demoModel());return {models:[demo],activeId:demo.id,versions:[],savedAt:'',importModel:(model)=>set(s=>({models:[...s.models.filter(m=>m.id!==model.id),migrateWorkforce(model)],activeId:model.id,savedAt:new Date().toISOString()})),setModel:(model)=>set(s=>({models:s.models.map(m=>m.id===model.id?migrateWorkforce(model):m),savedAt:new Date().toISOString()})),selectModel:(activeId)=>set({activeId}),newModel:()=>{const m=demoModel();m.id=id();m.name='Untitled Financial Model';m.projects=[];m.corporate=[];m.resources=[];set(s=>({models:[...s.models,m],activeId:m.id}));},saveVersion:(name)=>{const m=get().models.find(m=>m.id===get().activeId)!;set(s=>({versions:[{id:id(),name,date:new Date().toISOString(),model:structuredClone(m)},...s.versions]}));},restore:(versionId)=>{const v=get().versions.find(v=>v.id===versionId);if(v)get().setModel(structuredClone(v.model));},loadCloud:(incoming)=>set(s=>{const merged=mergeCloudModels(s.models,incoming);return {models:merged.models,activeId:incoming[0]?.id||s.activeId,versions:[...merged.backups.map(model=>({id:id(),name:'Before cloud load',date:new Date().toISOString(),model})),...s.versions],savedAt:new Date().toISOString()}}),mergeVersions:(versions)=>set(s=>({versions:[...versions,...s.versions.filter(v=>!versions.some(x=>x.id===v.id))]}))};},{name:'development-modeler-v1',version:4,migrate:(persisted)=>migrateLegacyCalendar(persisted as Store),merge:(persisted,current)=>{const saved=persisted as Partial<Store>;const models=saved.models||current.models;const versions=[...(saved.versions||[])];models.forEach(m=>{if(m.workforce?.departments.some(d=>d.projectId||d.allocation!=='Corporate')&&!versions.some(v=>v.model.id===m.id&&v.name==='Before company payroll'))versions.unshift({id:id(),name:'Before company payroll',date:new Date().toISOString(),model:m});if(!m.workforce&&!versions.some(v=>v.model.id===m.id&&v.name==='Before Employees migration'))versions.unshift({id:id(),name:'Before Employees migration',date:new Date().toISOString(),model:m});});return {...current,...saved,models:models.map(migrateWorkforce),versions};}}));
