'use client';
import {appPath} from '@/lib/app-path';
import {AccessRequests} from './access-requests';
import {stableJSON} from '@/lib/stable-json';
import {migrateWorkforce} from '@/lib/workforce';
import {tr,useLanguage} from '@/lib/i18n';
import {useState} from 'react';
import {Link2,Copy,LockKeyhole} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {FinancialModel} from '@/types/model';
export function ShareModel({model}:{model:FinancialModel}){useLanguage();const [link,setLink]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const sb=supabase();return <div className="stack"><h3>{model.name}</h3><div className="notice row"><LockKeyhole size={18}/><span>{tr("Only this model is shared for 7 days. The viewer has no editing, copying, sign-in or workspace navigation controls. The link shows the latest cloud-saved version.")}</span></div>{!sb?<p>{tr("Connect Supabase in Settings and save this model to cloud to create a sharing link.")}</p>:<button className="btn dark" disabled={busy} onClick={async()=>{setBusy(true);setLink('');setMessage('');try{const {data:saved,error:readError}=await sb.from('financial_models').select('data').eq('id',model.id).maybeSingle();if(readError)throw readError;if(!saved||stableJSON(migrateWorkforce(saved.data))!==stableJSON(migrateWorkforce(model)))throw new Error(tr('Save the latest changes to this model in the cloud before creating a viewing link.'));const {data,error}=await sb.rpc('create_model_share',{model_uuid:model.id});if(error)throw error;setLink(`${location.origin}${appPath('/shared/')}?token=${encodeURIComponent(data)}`);setMessage(tr('Link created. It expires in 7 days.'))}catch(e){setMessage(e instanceof Error?e.message:'Save this model to cloud and sign in before sharing.')}finally{setBusy(false)}}}><Link2 size={16}/>{tr(" Create read-only link")}</button>}{link&&<><input aria-label={tr("Read-only model link")} value={link} readOnly/><button className="btn" onClick={()=>navigator.clipboard.writeText(link).then(()=>setMessage('Link copied.')).catch(()=>setMessage('Select and copy the link manually.'))}><Copy size={15}/>{tr(" Copy link")}</button></>}{message&&<p role="status">{message}</p>}<details><summary>{tr('Editing access')}</summary><AccessRequests modelId={model.id}/></details></div>}
